FROM ruby:2.6.3
  #ベースイメージを指定
RUN apt-get update -qq && apt-get install -y build-essential nodejs
  #nodejsをインストール
RUN mkdir /app
WORKDIR /app
  #作業ディレクトリ指定
COPY Gemfile /app/Gemfile
  #ファイルやディレクトリを取得（ローカルのみ）
COPY Gemfile.lock /app/Gemfile.lock
RUN bundle install
COPY . /app
CMD ["rails", "s"]
