# version: 2.1
# orbs:
#   ruby: circleci/ruby@0.1.2

# jobs:
#   build:
#     docker:
#       - image: circleci/ruby:2.6.3-stretch-node
#     executor: ruby/default
#     steps:
#       - checkout
#       - run:
#           name: Which bundler?
#           command: bundle -v
#       - ruby/bundle-install

version: 2.1
jobs:
  build:
    docker:
    - image: circleci/ruby:2.6.3-node-browsers
      environment:
        - BUNDLER_VERSION: 2.0.2
        - RAILS_ENV: 'test'
    - image: circleci/mysql:5.6
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        - MYSQL_ROOT_HOST: '127.0.0.1'

    working_directory: ~/tadakashi_app  #自身のアプリディレクトリ名を設定
